# Generated by Django 5.0.2 on 2024-03-01 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrudeSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=255, unique=True)),
                ('sample_type', models.CharField(choices=[('CRUDE', 'Crude Sample'), ('ALIQUOT', 'Crude Aliquot'), ('DNA', 'DNA Extract'), ('RNA', 'RNA Extract'), ('SEQ', 'Sequence Library')], max_length=10)),
                ('date_created', models.DateField()),
                ('freezer_ID', models.CharField(max_length=100)),
                ('shelf_ID', models.CharField(max_length=100)),
                ('box_ID', models.CharField(max_length=100)),
                ('your_id', models.CharField(max_length=50)),
                ('collection_date', models.DateField()),
                ('sample_source', models.CharField(choices=[('Stool', 'Stool'), ('Nasal', 'Nasal Swab'), ('Skin', 'Skin Swab'), ('Oral', 'Oral Swab'), ('Other', 'Other')], default='', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aliquot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=255, unique=True)),
                ('sample_type', models.CharField(choices=[('CRUDE', 'Crude Sample'), ('ALIQUOT', 'Crude Aliquot'), ('DNA', 'DNA Extract'), ('RNA', 'RNA Extract'), ('SEQ', 'Sequence Library')], max_length=10)),
                ('date_created', models.DateField()),
                ('freezer_ID', models.CharField(max_length=100)),
                ('shelf_ID', models.CharField(max_length=100)),
                ('box_ID', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='sampletracking.crudesample')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=255, unique=True)),
                ('sample_type', models.CharField(choices=[('CRUDE', 'Crude Sample'), ('ALIQUOT', 'Crude Aliquot'), ('DNA', 'DNA Extract'), ('RNA', 'RNA Extract'), ('SEQ', 'Sequence Library')], max_length=10)),
                ('date_created', models.DateField()),
                ('freezer_ID', models.CharField(max_length=100)),
                ('shelf_ID', models.CharField(max_length=100)),
                ('box_ID', models.CharField(max_length=100)),
                ('extract_type', models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA'), ('cfDNA', 'cfDNA')], default='DNA', max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='sampletracking.aliquot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SequenceLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=255, unique=True)),
                ('sample_type', models.CharField(choices=[('CRUDE', 'Crude Sample'), ('ALIQUOT', 'Crude Aliquot'), ('DNA', 'DNA Extract'), ('RNA', 'RNA Extract'), ('SEQ', 'Sequence Library')], max_length=10)),
                ('date_created', models.DateField()),
                ('freezer_ID', models.CharField(max_length=100)),
                ('shelf_ID', models.CharField(max_length=100)),
                ('box_ID', models.CharField(max_length=100)),
                ('library_type', models.CharField(choices=[('Nextera', 'Nextera'), ('SMARTer', 'SMARTer'), ('QIA_COVID', 'QIA_COVID')], default='DNA', max_length=100)),
                ('nindex', models.CharField(choices=[('N701', 'N701'), ('N702', 'N702'), ('N703', 'N703'), ('N704', 'N704'), ('N705', 'N705'), ('N706', 'N706'), ('N707', 'N707'), ('N710', 'N710'), ('N711', 'N711'), ('N712', 'N712'), ('N714', 'N714'), ('N715', 'N715'), ('N716', 'N716'), ('N718', 'N718'), ('N719', 'N719'), ('N720', 'N720'), ('N721', 'N721'), ('N722', 'N722'), ('N723', 'N723'), ('N724', 'N724'), ('N726', 'N726'), ('N727', 'N727'), ('N728', 'N728'), ('N729', 'N729')], default='', max_length=100)),
                ('sindex', models.CharField(choices=[('S510', 'S510'), ('S502', 'S502'), ('S505', 'S505'), ('S506', 'S506'), ('S507', 'S507'), ('S510', 'S510'), ('S503', 'S503'), ('S511', 'S511'), ('S508', 'S508'), ('S516', 'S516'), ('S517', 'S517'), ('S518', 'S518'), ('S521', 'S521'), ('S515', 'S515'), ('S522', 'S522'), ('S520', 'S520'), ('S513', 'S513')], default='', max_length=100)),
                ('qubit_conc', models.FloatField()),
                ('diluted_qubit_conc', models.FloatField()),
                ('clean_library_conc', models.FloatField()),
                ('date_sequenced', models.DateField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='sampletracking.extract')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
