# Generated by Django 5.1.11 on 2025-09-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampletracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliquot',
            name='base_id',
            field=models.CharField(blank=True, editable=False, help_text='Base ID shared among related samples (e.g., ST-241219-001)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aliquot',
            name='sample_id',
            field=models.CharField(blank=True, editable=False, help_text='Full unique sample ID (e.g., ST-241219-001-CS)', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='crudesample',
            name='base_id',
            field=models.CharField(blank=True, editable=False, help_text='Base ID shared among related samples (e.g., ST-241219-001)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='crudesample',
            name='sample_id',
            field=models.CharField(blank=True, editable=False, help_text='Full unique sample ID (e.g., ST-241219-001-CS)', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='extract',
            name='base_id',
            field=models.CharField(blank=True, editable=False, help_text='Base ID shared among related samples (e.g., ST-241219-001)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='extract',
            name='sample_id',
            field=models.CharField(blank=True, editable=False, help_text='Full unique sample ID (e.g., ST-241219-001-CS)', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalaliquot',
            name='base_id',
            field=models.CharField(blank=True, editable=False, help_text='Base ID shared among related samples (e.g., ST-241219-001)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalaliquot',
            name='sample_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Full unique sample ID (e.g., ST-241219-001-CS)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalcrudesample',
            name='base_id',
            field=models.CharField(blank=True, editable=False, help_text='Base ID shared among related samples (e.g., ST-241219-001)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalcrudesample',
            name='sample_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Full unique sample ID (e.g., ST-241219-001-CS)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalextract',
            name='base_id',
            field=models.CharField(blank=True, editable=False, help_text='Base ID shared among related samples (e.g., ST-241219-001)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalextract',
            name='sample_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Full unique sample ID (e.g., ST-241219-001-CS)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalsequencelibrary',
            name='base_id',
            field=models.CharField(blank=True, editable=False, help_text='Base ID shared among related samples (e.g., ST-241219-001)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalsequencelibrary',
            name='sample_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Full unique sample ID (e.g., ST-241219-001-CS)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sequencelibrary',
            name='base_id',
            field=models.CharField(blank=True, editable=False, help_text='Base ID shared among related samples (e.g., ST-241219-001)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sequencelibrary',
            name='sample_id',
            field=models.CharField(blank=True, editable=False, help_text='Full unique sample ID (e.g., ST-241219-001-CS)', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='crudesample',
            name='sample_source',
            field=models.CharField(choices=[('Stool', 'Stool'), ('Oral', 'Oral Swab'), ('Nasal', 'Nasal Swab'), ('Skin', 'Skin Swab'), ('Blood', 'Blood'), ('Tissue', 'Tissue'), ('Isolate', 'Isolate'), ('Other', 'Other')], default='', help_text='Source of the sample', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcrudesample',
            name='sample_source',
            field=models.CharField(choices=[('Stool', 'Stool'), ('Oral', 'Oral Swab'), ('Nasal', 'Nasal Swab'), ('Skin', 'Skin Swab'), ('Blood', 'Blood'), ('Tissue', 'Tissue'), ('Isolate', 'Isolate'), ('Other', 'Other')], default='', help_text='Source of the sample', max_length=100),
        ),
    ]
