# Generated by Django 5.1.11 on 2025-09-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampletracking', '0002_aliquot_base_id_aliquot_sample_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliquot',
            name='investigator',
            field=models.CharField(blank=True, help_text='Principal investigator or responsible party', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aliquot',
            name='patient_type',
            field=models.CharField(blank=True, help_text='Patient classification (e.g., IBD, Control, Cancer)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aliquot',
            name='project_name',
            field=models.CharField(blank=True, help_text='Name of the project or study this sample belongs to', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aliquot',
            name='study_id',
            field=models.CharField(blank=True, help_text='External study identifier or protocol number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crudesample',
            name='investigator',
            field=models.CharField(blank=True, help_text='Principal investigator or responsible party', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='crudesample',
            name='patient_type',
            field=models.CharField(blank=True, help_text='Patient classification (e.g., IBD, Control, Cancer)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crudesample',
            name='project_name',
            field=models.CharField(blank=True, help_text='Name of the project or study this sample belongs to', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='crudesample',
            name='study_id',
            field=models.CharField(blank=True, help_text='External study identifier or protocol number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extract',
            name='investigator',
            field=models.CharField(blank=True, help_text='Principal investigator or responsible party', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='extract',
            name='patient_type',
            field=models.CharField(blank=True, help_text='Patient classification (e.g., IBD, Control, Cancer)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extract',
            name='project_name',
            field=models.CharField(blank=True, help_text='Name of the project or study this sample belongs to', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='extract',
            name='study_id',
            field=models.CharField(blank=True, help_text='External study identifier or protocol number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalaliquot',
            name='investigator',
            field=models.CharField(blank=True, help_text='Principal investigator or responsible party', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalaliquot',
            name='patient_type',
            field=models.CharField(blank=True, help_text='Patient classification (e.g., IBD, Control, Cancer)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalaliquot',
            name='project_name',
            field=models.CharField(blank=True, help_text='Name of the project or study this sample belongs to', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalaliquot',
            name='study_id',
            field=models.CharField(blank=True, help_text='External study identifier or protocol number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcrudesample',
            name='investigator',
            field=models.CharField(blank=True, help_text='Principal investigator or responsible party', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalcrudesample',
            name='patient_type',
            field=models.CharField(blank=True, help_text='Patient classification (e.g., IBD, Control, Cancer)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcrudesample',
            name='project_name',
            field=models.CharField(blank=True, help_text='Name of the project or study this sample belongs to', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalcrudesample',
            name='study_id',
            field=models.CharField(blank=True, help_text='External study identifier or protocol number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalextract',
            name='investigator',
            field=models.CharField(blank=True, help_text='Principal investigator or responsible party', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalextract',
            name='patient_type',
            field=models.CharField(blank=True, help_text='Patient classification (e.g., IBD, Control, Cancer)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalextract',
            name='project_name',
            field=models.CharField(blank=True, help_text='Name of the project or study this sample belongs to', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalextract',
            name='study_id',
            field=models.CharField(blank=True, help_text='External study identifier or protocol number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalsequencelibrary',
            name='data_file_location',
            field=models.CharField(blank=True, help_text='Path to the actual sequence data files', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalsequencelibrary',
            name='investigator',
            field=models.CharField(blank=True, help_text='Principal investigator or responsible party', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalsequencelibrary',
            name='is_legacy_import',
            field=models.BooleanField(default=False, help_text='Indicates if this record was imported from historical data'),
        ),
        migrations.AddField(
            model_name='historicalsequencelibrary',
            name='legacy_sequence_filename',
            field=models.CharField(blank=True, help_text='Original filename for historical/legacy sequence data (without _R1/_R2 suffix)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalsequencelibrary',
            name='patient_type',
            field=models.CharField(blank=True, help_text='Patient classification (e.g., IBD, Control, Cancer)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalsequencelibrary',
            name='project_name',
            field=models.CharField(blank=True, help_text='Name of the project or study this sample belongs to', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalsequencelibrary',
            name='study_id',
            field=models.CharField(blank=True, help_text='External study identifier or protocol number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sequencelibrary',
            name='data_file_location',
            field=models.CharField(blank=True, help_text='Path to the actual sequence data files', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sequencelibrary',
            name='investigator',
            field=models.CharField(blank=True, help_text='Principal investigator or responsible party', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sequencelibrary',
            name='is_legacy_import',
            field=models.BooleanField(default=False, help_text='Indicates if this record was imported from historical data'),
        ),
        migrations.AddField(
            model_name='sequencelibrary',
            name='legacy_sequence_filename',
            field=models.CharField(blank=True, help_text='Original filename for historical/legacy sequence data (without _R1/_R2 suffix)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sequencelibrary',
            name='patient_type',
            field=models.CharField(blank=True, help_text='Patient classification (e.g., IBD, Control, Cancer)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sequencelibrary',
            name='project_name',
            field=models.CharField(blank=True, help_text='Name of the project or study this sample belongs to', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sequencelibrary',
            name='study_id',
            field=models.CharField(blank=True, help_text='External study identifier or protocol number', max_length=100, null=True),
        ),
    ]
