# Generated by Django 5.1.11 on 2025-09-20 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampletracking', '0003_aliquot_investigator_aliquot_patient_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crudesample',
            name='isolate_source',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Blood', 'Blood'), ('Urine', 'Urine'), ('Wound', 'Wound'), ('Stool', 'Stool'), ('Laboratory', 'Laboratory'), ('Other', 'Other')], help_text="Source of the isolate (only applicable when sample source is 'Isolate')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalcrudesample',
            name='isolate_source',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Blood', 'Blood'), ('Urine', 'Urine'), ('Wound', 'Wound'), ('Stool', 'Stool'), ('Laboratory', 'Laboratory'), ('Other', 'Other')], help_text="Source of the isolate (only applicable when sample source is 'Isolate')", max_length=50, null=True),
        ),
    ]
