# Generated by Django 5.1.11 on 2025-09-20 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampletracking', '0004_crudesample_isolate_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crudesample',
            options={'verbose_name': 'Parent Sample', 'verbose_name_plural': 'Parent Samples'},
        ),
        migrations.AlterModelOptions(
            name='historicalcrudesample',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Parent Sample', 'verbose_name_plural': 'historical Parent Samples'},
        ),
        migrations.AlterField(
            model_name='aliquot',
            name='parent_barcode',
            field=models.ForeignKey(help_text='The parent sample this aliquot was derived from', on_delete=django.db.models.deletion.PROTECT, related_name='aliquots', to='sampletracking.crudesample', to_field='barcode'),
        ),
        migrations.AlterField(
            model_name='historicalaliquot',
            name='parent_barcode',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The parent sample this aliquot was derived from', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sampletracking.crudesample', to_field='barcode'),
        ),
        migrations.AlterField(
            model_name='historicalsequencelibrary',
            name='library_type',
            field=models.CharField(choices=[('Nextera_XT', 'Illumina Nextera XT DNA Library Prep'), ('Nextera_Flex', 'Illumina Nextera DNA Flex / DNA Prep'), ('TruSeq_Nano', 'Illumina TruSeq Nano DNA'), ('NEBNext_Ultra_DNA', 'NEBNext Ultra II DNA Library Prep'), ('QIAseq_FX', 'QIAseq FX DNA Library Kit'), ('Swift_Accel', 'Swift Biosciences Accel-NGS 2S DNA Library Kit'), ('PacBio_SMRTbell', 'PacBio SMRTbell Express Template Prep Kit'), ('ONT_Ligation', 'Oxford Nanopore Ligation Sequencing Kit'), ('ONT_Rapid', 'Oxford Nanopore Rapid Sequencing Kit'), ('Twist_Hybrid', 'Twist Target Enrichment (Hybrid Capture)'), ('Agilent_SureSelect', 'Agilent SureSelect Target Enrichment'), ('16S_Metagenomic', '16S Metagenomic Sequencing Library Prep'), ('ITS_Amplicon', 'ITS Amplicon Library Prep (fungal)'), ('TruSeq_Total_RNA', 'Illumina TruSeq Stranded Total RNA (Ribo-Zero)'), ('NEBNext_RNA_Ribo', 'NEBNext rRNA Depletion + Ultra II RNA Prep'), ('RiboZero_Plus', 'Ribo-Zero Plus rRNA Depletion Kit'), ('SMARTer_Total_Microbes', 'SMARTer Stranded Total RNA-Seq (microbes)'), ('SMARTer_Pico', 'SMARTer Stranded Total RNA-Seq v2 - Pico Input'), ('QIAseq_FastSelect', 'QIAseq FastSelect rRNA Removal + RNA Library'), ('Lexogen_RiboCop', 'Lexogen RiboCop rRNA Depletion + CORALL RNA-Seq'), ('ONT_Direct_RNA', 'Oxford Nanopore Direct RNA Sequencing Kit'), ('PacBio_IsoSeq', 'PacBio Iso-Seq Express Template Prep'), ('TruSeq_mRNA', 'Illumina TruSeq Stranded mRNA Library Prep'), ('TruSeq_SmallRNA', 'Illumina TruSeq Small RNA Library Prep'), ('NEBNext_Ultra_RNA', 'NEBNext Ultra II Directional RNA Library Prep'), ('SMART_Seq_v4', 'SMART-Seq v4 Ultra Low Input RNA Kit'), ('QuantSeq_3prime', 'QuantSeq 3′ mRNA-Seq Library Prep (Lexogen)'), ('10x_3prime', '10x Genomics Chromium Single Cell 3′ Gene Expression'), ('10x_5prime', '10x Genomics Chromium Single Cell 5′ Gene Expression'), ('10x_Multiome', '10x Genomics Multiome (ATAC + RNA)'), ('SMART_Seq2', 'SMART-Seq2'), ('SMART_Seq3', 'SMART-Seq3'), ('CEL_Seq2', 'CEL-Seq2'), ('Drop_seq', 'Drop-seq (academic protocol)'), ('inDrops', 'inDrops (academic protocol)'), ('Seq_Well', 'Seq-Well (academic protocol)'), ('10x_Visium', '10x Genomics Visium Spatial Gene Expression'), ('NanoString_GeoMx', 'NanoString GeoMx DSP RNA Library Prep'), ('Slide_seq', 'Slide-seq / Slide-seqV2'), ('SMART_Seq_HT', 'SMART-Seq HT Kit (high-throughput)'), ('SMART_Seq_Nucleus', 'SMARTer Stranded Total RNA-Seq (Single Nucleus)'), ('Nextera', 'Nextera (legacy)'), ('SMARTer', 'SMARTer (legacy)'), ('QIA_COVID', 'QIA_COVID'), ('TruSeq', 'TruSeq (legacy)'), ('Other', 'Other/Custom')], default='Nextera_XT', help_text='Type of sequencing library preparation method', max_length=100),
        ),
        migrations.AlterField(
            model_name='sequencelibrary',
            name='library_type',
            field=models.CharField(choices=[('Nextera_XT', 'Illumina Nextera XT DNA Library Prep'), ('Nextera_Flex', 'Illumina Nextera DNA Flex / DNA Prep'), ('TruSeq_Nano', 'Illumina TruSeq Nano DNA'), ('NEBNext_Ultra_DNA', 'NEBNext Ultra II DNA Library Prep'), ('QIAseq_FX', 'QIAseq FX DNA Library Kit'), ('Swift_Accel', 'Swift Biosciences Accel-NGS 2S DNA Library Kit'), ('PacBio_SMRTbell', 'PacBio SMRTbell Express Template Prep Kit'), ('ONT_Ligation', 'Oxford Nanopore Ligation Sequencing Kit'), ('ONT_Rapid', 'Oxford Nanopore Rapid Sequencing Kit'), ('Twist_Hybrid', 'Twist Target Enrichment (Hybrid Capture)'), ('Agilent_SureSelect', 'Agilent SureSelect Target Enrichment'), ('16S_Metagenomic', '16S Metagenomic Sequencing Library Prep'), ('ITS_Amplicon', 'ITS Amplicon Library Prep (fungal)'), ('TruSeq_Total_RNA', 'Illumina TruSeq Stranded Total RNA (Ribo-Zero)'), ('NEBNext_RNA_Ribo', 'NEBNext rRNA Depletion + Ultra II RNA Prep'), ('RiboZero_Plus', 'Ribo-Zero Plus rRNA Depletion Kit'), ('SMARTer_Total_Microbes', 'SMARTer Stranded Total RNA-Seq (microbes)'), ('SMARTer_Pico', 'SMARTer Stranded Total RNA-Seq v2 - Pico Input'), ('QIAseq_FastSelect', 'QIAseq FastSelect rRNA Removal + RNA Library'), ('Lexogen_RiboCop', 'Lexogen RiboCop rRNA Depletion + CORALL RNA-Seq'), ('ONT_Direct_RNA', 'Oxford Nanopore Direct RNA Sequencing Kit'), ('PacBio_IsoSeq', 'PacBio Iso-Seq Express Template Prep'), ('TruSeq_mRNA', 'Illumina TruSeq Stranded mRNA Library Prep'), ('TruSeq_SmallRNA', 'Illumina TruSeq Small RNA Library Prep'), ('NEBNext_Ultra_RNA', 'NEBNext Ultra II Directional RNA Library Prep'), ('SMART_Seq_v4', 'SMART-Seq v4 Ultra Low Input RNA Kit'), ('QuantSeq_3prime', 'QuantSeq 3′ mRNA-Seq Library Prep (Lexogen)'), ('10x_3prime', '10x Genomics Chromium Single Cell 3′ Gene Expression'), ('10x_5prime', '10x Genomics Chromium Single Cell 5′ Gene Expression'), ('10x_Multiome', '10x Genomics Multiome (ATAC + RNA)'), ('SMART_Seq2', 'SMART-Seq2'), ('SMART_Seq3', 'SMART-Seq3'), ('CEL_Seq2', 'CEL-Seq2'), ('Drop_seq', 'Drop-seq (academic protocol)'), ('inDrops', 'inDrops (academic protocol)'), ('Seq_Well', 'Seq-Well (academic protocol)'), ('10x_Visium', '10x Genomics Visium Spatial Gene Expression'), ('NanoString_GeoMx', 'NanoString GeoMx DSP RNA Library Prep'), ('Slide_seq', 'Slide-seq / Slide-seqV2'), ('SMART_Seq_HT', 'SMART-Seq HT Kit (high-throughput)'), ('SMART_Seq_Nucleus', 'SMARTer Stranded Total RNA-Seq (Single Nucleus)'), ('Nextera', 'Nextera (legacy)'), ('SMARTer', 'SMARTer (legacy)'), ('QIA_COVID', 'QIA_COVID'), ('TruSeq', 'TruSeq (legacy)'), ('Other', 'Other/Custom')], default='Nextera_XT', help_text='Type of sequencing library preparation method', max_length=100),
        ),
    ]
