# Generated by Django 5.0.2 on 2025-07-15 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampletracking', '0004_alter_aliquot_options_alter_crudesample_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliquot',
            name='parent_barcode',
            field=models.ForeignKey(blank=True, help_text='The crude sample this aliquot was derived from', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aliquots', to='sampletracking.crudesample', to_field='barcode'),
        ),
        migrations.AlterField(
            model_name='extract',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The aliquot this extract was derived from', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extracts', to='sampletracking.aliquot', to_field='barcode'),
        ),
    ]
