# Generated by Django 5.0.2 on 2025-07-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampletracking', '0006_enforce_parent_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliquot',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_PROCESS', 'In Process'), ('EXHAUSTED', 'Exhausted'), ('CONTAMINATED', 'Contaminated'), ('ARCHIVED', 'Archived')], default='AVAILABLE', help_text='Current status of the sample', max_length=20),
        ),
        migrations.AddField(
            model_name='crudesample',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_PROCESS', 'In Process'), ('EXHAUSTED', 'Exhausted'), ('CONTAMINATED', 'Contaminated'), ('ARCHIVED', 'Archived')], default='AVAILABLE', help_text='Current status of the sample', max_length=20),
        ),
        migrations.AddField(
            model_name='extract',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_PROCESS', 'In Process'), ('EXHAUSTED', 'Exhausted'), ('CONTAMINATED', 'Contaminated'), ('ARCHIVED', 'Archived')], default='AVAILABLE', help_text='Current status of the sample', max_length=20),
        ),
        migrations.AddField(
            model_name='sequencelibrary',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_PROCESS', 'In Process'), ('EXHAUSTED', 'Exhausted'), ('CONTAMINATED', 'Contaminated'), ('ARCHIVED', 'Archived')], default='AVAILABLE', help_text='Current status of the sample', max_length=20),
        ),
    ]
