# Generated by Django 5.1.11 on 2025-07-16 02:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampletracking', '0013_fix_subject_id_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='extract',
            name='extract_volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final extract volume in mL (for Metabolomics/Antimicrobials)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='extract',
            name='extraction_method',
            field=models.CharField(blank=True, help_text='Extraction method used (for DNA/RNA extracts)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extract',
            name='extraction_solvent',
            field=models.CharField(blank=True, help_text='Solvent used for extraction (for Metabolomics/Antimicrobials)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extract',
            name='sample_weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Sample weight in grams (for Metabolomics/Antimicrobials)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='extract',
            name='solvent_volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume of solvent used in mL (for Metabolomics/Antimicrobials)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalextract',
            name='extract_volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final extract volume in mL (for Metabolomics/Antimicrobials)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalextract',
            name='extraction_method',
            field=models.CharField(blank=True, help_text='Extraction method used (for DNA/RNA extracts)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalextract',
            name='extraction_solvent',
            field=models.CharField(blank=True, help_text='Solvent used for extraction (for Metabolomics/Antimicrobials)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalextract',
            name='sample_weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Sample weight in grams (for Metabolomics/Antimicrobials)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalextract',
            name='solvent_volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Volume of solvent used in mL (for Metabolomics/Antimicrobials)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='extract',
            name='extract_type',
            field=models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA'), ('cfDNA', 'cfDNA'), ('Protein', 'Protein'), ('Metabolomics', 'Metabolomics'), ('Antimicrobials', 'Antimicrobials'), ('Other', 'Other')], default='DNA', help_text='Type of extract', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalextract',
            name='extract_type',
            field=models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA'), ('cfDNA', 'cfDNA'), ('Protein', 'Protein'), ('Metabolomics', 'Metabolomics'), ('Antimicrobials', 'Antimicrobials'), ('Other', 'Other')], default='DNA', help_text='Type of extract', max_length=100),
        ),
    ]
