# Generated by Django 5.1.11 on 2025-07-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampletracking', '0015_remove_crudesample_sampletrack_your_id_2965c3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliquot',
            name='container_type',
            field=models.CharField(blank=True, choices=[('box', 'Box'), ('plate', 'Plate')], default='box', help_text='Type of container (box or plate)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='crudesample',
            name='container_type',
            field=models.CharField(blank=True, choices=[('box', 'Box'), ('plate', 'Plate')], default='box', help_text='Type of container (box or plate)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='extract',
            name='container_type',
            field=models.CharField(blank=True, choices=[('box', 'Box'), ('plate', 'Plate')], default='box', help_text='Type of container (box or plate)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalaliquot',
            name='container_type',
            field=models.CharField(blank=True, choices=[('box', 'Box'), ('plate', 'Plate')], default='box', help_text='Type of container (box or plate)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalcrudesample',
            name='container_type',
            field=models.CharField(blank=True, choices=[('box', 'Box'), ('plate', 'Plate')], default='box', help_text='Type of container (box or plate)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalextract',
            name='container_type',
            field=models.CharField(blank=True, choices=[('box', 'Box'), ('plate', 'Plate')], default='box', help_text='Type of container (box or plate)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalplate',
            name='container_type',
            field=models.CharField(blank=True, choices=[('box', 'Box'), ('plate', 'Plate')], default='box', help_text='Type of container (box or plate)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalsequencelibrary',
            name='container_type',
            field=models.CharField(blank=True, choices=[('box', 'Box'), ('plate', 'Plate')], default='box', help_text='Type of container (box or plate)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='container_type',
            field=models.CharField(blank=True, choices=[('box', 'Box'), ('plate', 'Plate')], default='box', help_text='Type of container (box or plate)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sequencelibrary',
            name='container_type',
            field=models.CharField(blank=True, choices=[('box', 'Box'), ('plate', 'Plate')], default='box', help_text='Type of container (box or plate)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aliquot',
            name='box_ID',
            field=models.CharField(blank=True, help_text='Identifier for the container where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aliquot',
            name='well_ID',
            field=models.CharField(blank=True, help_text='Well position in the container (e.g., A1, B2, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crudesample',
            name='box_ID',
            field=models.CharField(blank=True, help_text='Identifier for the container where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crudesample',
            name='well_ID',
            field=models.CharField(blank=True, help_text='Well position in the container (e.g., A1, B2, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='extract',
            name='box_ID',
            field=models.CharField(blank=True, help_text='Identifier for the container where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extract',
            name='well_ID',
            field=models.CharField(blank=True, help_text='Well position in the container (e.g., A1, B2, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaliquot',
            name='box_ID',
            field=models.CharField(blank=True, help_text='Identifier for the container where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaliquot',
            name='well_ID',
            field=models.CharField(blank=True, help_text='Well position in the container (e.g., A1, B2, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcrudesample',
            name='box_ID',
            field=models.CharField(blank=True, help_text='Identifier for the container where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcrudesample',
            name='well_ID',
            field=models.CharField(blank=True, help_text='Well position in the container (e.g., A1, B2, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalextract',
            name='box_ID',
            field=models.CharField(blank=True, help_text='Identifier for the container where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalextract',
            name='well_ID',
            field=models.CharField(blank=True, help_text='Well position in the container (e.g., A1, B2, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalplate',
            name='box_ID',
            field=models.CharField(blank=True, help_text='Identifier for the container where this plate is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalplate',
            name='well_ID',
            field=models.CharField(blank=True, help_text='Well position in the container (e.g., A1, B2, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsequencelibrary',
            name='box_ID',
            field=models.CharField(blank=True, help_text='Identifier for the container where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsequencelibrary',
            name='well_ID',
            field=models.CharField(blank=True, help_text='Well position in the container (e.g., A1, B2, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='box_ID',
            field=models.CharField(blank=True, help_text='Identifier for the container where this plate is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='well_ID',
            field=models.CharField(blank=True, help_text='Well position in the container (e.g., A1, B2, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sequencelibrary',
            name='box_ID',
            field=models.CharField(blank=True, help_text='Identifier for the container where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sequencelibrary',
            name='well_ID',
            field=models.CharField(blank=True, help_text='Well position in the container (e.g., A1, B2, etc.)', max_length=50, null=True),
        ),
    ]
