# Generated by Django 5.1.11 on 2025-09-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampletracking', '0019_remove_crudesample_sampletrack_your_id_2965c3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='crudesample',
            name='sampletrack_your_id_2965c3_idx',
        ),
        migrations.RemoveField(
            model_name='crudesample',
            name='barcode_override_used',
        ),
        migrations.RemoveField(
            model_name='historicalcrudesample',
            name='barcode_override_used',
        ),
        migrations.AlterField(
            model_name='extract',
            name='extraction_method',
            field=models.CharField(blank=True, choices=[('PowerFecal Pro DNA', 'PowerFecal Pro DNA'), ('ZymoBIOMICS DNA', 'ZymoBIOMICS DNA'), ('RNeasy PowerMicrobiome', 'RNeasy PowerMicrobiome'), ('ZymoBIOMICS RNA', 'ZymoBIOMICS RNA'), ('AllPrep PowerFecal DNA/RNA', 'AllPrep PowerFecal DNA/RNA'), ('ZymoBIOMICS DNA/RNA', 'ZymoBIOMICS DNA/RNA'), ('Other', 'Other')], default='PowerFecal Pro DNA', help_text='Extraction method used (for DNA/RNA extracts)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalextract',
            name='extraction_method',
            field=models.CharField(blank=True, choices=[('PowerFecal Pro DNA', 'PowerFecal Pro DNA'), ('ZymoBIOMICS DNA', 'ZymoBIOMICS DNA'), ('RNeasy PowerMicrobiome', 'RNeasy PowerMicrobiome'), ('ZymoBIOMICS RNA', 'ZymoBIOMICS RNA'), ('AllPrep PowerFecal DNA/RNA', 'AllPrep PowerFecal DNA/RNA'), ('ZymoBIOMICS DNA/RNA', 'ZymoBIOMICS DNA/RNA'), ('Other', 'Other')], default='PowerFecal Pro DNA', help_text='Extraction method used (for DNA/RNA extracts)', max_length=255, null=True),
        ),
    ]
