# Generated by Django 5.0.2 on 2025-07-15 09:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampletracking', '0007_aliquot_status_crudesample_status_extract_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencelibrary',
            name='well',
            field=models.CharField(blank=True, help_text='Well position, e.g., A1, H12', max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(help_text='Unique identifier for this plate', max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_-]+$', 'Barcode can only contain alphanumeric characters, underscores, and hyphens.')])),
                ('plate_type', models.CharField(choices=[('96', '96-Well'), ('384', '384-Well')], default='96', help_text='Type of plate (96-well or 384-well)', max_length=3)),
                ('freezer_ID', models.CharField(blank=True, help_text='Identifier for the freezer where this plate is stored', max_length=100, null=True)),
                ('shelf_ID', models.CharField(blank=True, help_text='Identifier for the shelf where this plate is stored', max_length=100, null=True)),
                ('box_ID', models.CharField(blank=True, help_text='Identifier for the box where this plate is stored', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this plate', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plate',
                'verbose_name_plural': 'Plates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sequencelibrary',
            name='plate',
            field=models.ForeignKey(blank=True, help_text='The plate this library is in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libraries', to='sampletracking.plate'),
        ),
        migrations.AlterUniqueTogether(
            name='sequencelibrary',
            unique_together={('plate', 'well')},
        ),
    ]
