# Generated by Django 5.1.11 on 2025-07-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampletracking', '0009_historicalaliquot_historicalcrudesample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliquot',
            name='box_ID',
            field=models.CharField(blank=True, help_text='Identifier for the box where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aliquot',
            name='freezer_ID',
            field=models.CharField(blank=True, help_text='Identifier for the freezer where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aliquot',
            name='shelf_ID',
            field=models.CharField(blank=True, help_text='Identifier for the shelf where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aliquot',
            name='status',
            field=models.CharField(choices=[('AWAITING_RECEIPT', 'Awaiting Receipt'), ('AVAILABLE', 'Available'), ('IN_PROCESS', 'In Process'), ('EXHAUSTED', 'Exhausted'), ('CONTAMINATED', 'Contaminated'), ('ARCHIVED', 'Archived')], default='AWAITING_RECEIPT', help_text='The current status of the sample', max_length=20),
        ),
        migrations.AlterField(
            model_name='crudesample',
            name='box_ID',
            field=models.CharField(blank=True, help_text='Identifier for the box where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crudesample',
            name='freezer_ID',
            field=models.CharField(blank=True, help_text='Identifier for the freezer where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crudesample',
            name='shelf_ID',
            field=models.CharField(blank=True, help_text='Identifier for the shelf where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crudesample',
            name='status',
            field=models.CharField(choices=[('AWAITING_RECEIPT', 'Awaiting Receipt'), ('AVAILABLE', 'Available'), ('IN_PROCESS', 'In Process'), ('EXHAUSTED', 'Exhausted'), ('CONTAMINATED', 'Contaminated'), ('ARCHIVED', 'Archived')], default='AWAITING_RECEIPT', help_text='The current status of the sample', max_length=20),
        ),
        migrations.AlterField(
            model_name='extract',
            name='box_ID',
            field=models.CharField(blank=True, help_text='Identifier for the box where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extract',
            name='freezer_ID',
            field=models.CharField(blank=True, help_text='Identifier for the freezer where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extract',
            name='shelf_ID',
            field=models.CharField(blank=True, help_text='Identifier for the shelf where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extract',
            name='status',
            field=models.CharField(choices=[('AWAITING_RECEIPT', 'Awaiting Receipt'), ('AVAILABLE', 'Available'), ('IN_PROCESS', 'In Process'), ('EXHAUSTED', 'Exhausted'), ('CONTAMINATED', 'Contaminated'), ('ARCHIVED', 'Archived')], default='AWAITING_RECEIPT', help_text='The current status of the sample', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalaliquot',
            name='box_ID',
            field=models.CharField(blank=True, help_text='Identifier for the box where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaliquot',
            name='freezer_ID',
            field=models.CharField(blank=True, help_text='Identifier for the freezer where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaliquot',
            name='shelf_ID',
            field=models.CharField(blank=True, help_text='Identifier for the shelf where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalaliquot',
            name='status',
            field=models.CharField(choices=[('AWAITING_RECEIPT', 'Awaiting Receipt'), ('AVAILABLE', 'Available'), ('IN_PROCESS', 'In Process'), ('EXHAUSTED', 'Exhausted'), ('CONTAMINATED', 'Contaminated'), ('ARCHIVED', 'Archived')], default='AWAITING_RECEIPT', help_text='The current status of the sample', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalcrudesample',
            name='box_ID',
            field=models.CharField(blank=True, help_text='Identifier for the box where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcrudesample',
            name='freezer_ID',
            field=models.CharField(blank=True, help_text='Identifier for the freezer where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcrudesample',
            name='shelf_ID',
            field=models.CharField(blank=True, help_text='Identifier for the shelf where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcrudesample',
            name='status',
            field=models.CharField(choices=[('AWAITING_RECEIPT', 'Awaiting Receipt'), ('AVAILABLE', 'Available'), ('IN_PROCESS', 'In Process'), ('EXHAUSTED', 'Exhausted'), ('CONTAMINATED', 'Contaminated'), ('ARCHIVED', 'Archived')], default='AWAITING_RECEIPT', help_text='The current status of the sample', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalextract',
            name='box_ID',
            field=models.CharField(blank=True, help_text='Identifier for the box where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalextract',
            name='freezer_ID',
            field=models.CharField(blank=True, help_text='Identifier for the freezer where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalextract',
            name='shelf_ID',
            field=models.CharField(blank=True, help_text='Identifier for the shelf where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalextract',
            name='status',
            field=models.CharField(choices=[('AWAITING_RECEIPT', 'Awaiting Receipt'), ('AVAILABLE', 'Available'), ('IN_PROCESS', 'In Process'), ('EXHAUSTED', 'Exhausted'), ('CONTAMINATED', 'Contaminated'), ('ARCHIVED', 'Archived')], default='AWAITING_RECEIPT', help_text='The current status of the sample', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalsequencelibrary',
            name='box_ID',
            field=models.CharField(blank=True, help_text='Identifier for the box where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsequencelibrary',
            name='freezer_ID',
            field=models.CharField(blank=True, help_text='Identifier for the freezer where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsequencelibrary',
            name='shelf_ID',
            field=models.CharField(blank=True, help_text='Identifier for the shelf where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsequencelibrary',
            name='status',
            field=models.CharField(choices=[('AWAITING_RECEIPT', 'Awaiting Receipt'), ('AVAILABLE', 'Available'), ('IN_PROCESS', 'In Process'), ('EXHAUSTED', 'Exhausted'), ('CONTAMINATED', 'Contaminated'), ('ARCHIVED', 'Archived')], default='AWAITING_RECEIPT', help_text='The current status of the sample', max_length=20),
        ),
        migrations.AlterField(
            model_name='sequencelibrary',
            name='box_ID',
            field=models.CharField(blank=True, help_text='Identifier for the box where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sequencelibrary',
            name='freezer_ID',
            field=models.CharField(blank=True, help_text='Identifier for the freezer where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sequencelibrary',
            name='shelf_ID',
            field=models.CharField(blank=True, help_text='Identifier for the shelf where this sample is stored', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sequencelibrary',
            name='status',
            field=models.CharField(choices=[('AWAITING_RECEIPT', 'Awaiting Receipt'), ('AVAILABLE', 'Available'), ('IN_PROCESS', 'In Process'), ('EXHAUSTED', 'Exhausted'), ('CONTAMINATED', 'Contaminated'), ('ARCHIVED', 'Archived')], default='AWAITING_RECEIPT', help_text='The current status of the sample', max_length=20),
        ),
    ]
