# Generated by Django 5.1.11 on 2025-07-20 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampletracking', '0014_remove_crudesample_sampletrack_your_id_2965c3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliquot',
            name='shelf_ID',
        ),
        migrations.RemoveField(
            model_name='crudesample',
            name='shelf_ID',
        ),
        migrations.RemoveField(
            model_name='extract',
            name='shelf_ID',
        ),
        migrations.RemoveField(
            model_name='historicalaliquot',
            name='shelf_ID',
        ),
        migrations.RemoveField(
            model_name='historicalcrudesample',
            name='shelf_ID',
        ),
        migrations.RemoveField(
            model_name='historicalextract',
            name='shelf_ID',
        ),
        migrations.RemoveField(
            model_name='historicalplate',
            name='shelf_ID',
        ),
        migrations.RemoveField(
            model_name='historicalsequencelibrary',
            name='shelf_ID',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='shelf_ID',
        ),
        migrations.RemoveField(
            model_name='sequencelibrary',
            name='shelf_ID',
        ),
        migrations.AddField(
            model_name='aliquot',
            name='rack_ID',
            field=models.CharField(blank=True, help_text='Identifier for the rack where this sample is stored', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aliquot',
            name='well_ID',
            field=models.CharField(blank=True, help_text='Well position in the box (e.g., A1, B2, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='crudesample',
            name='rack_ID',
            field=models.CharField(blank=True, help_text='Identifier for the rack where this sample is stored', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crudesample',
            name='well_ID',
            field=models.CharField(blank=True, help_text='Well position in the box (e.g., A1, B2, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='extract',
            name='rack_ID',
            field=models.CharField(blank=True, help_text='Identifier for the rack where this sample is stored', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extract',
            name='well_ID',
            field=models.CharField(blank=True, help_text='Well position in the box (e.g., A1, B2, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalaliquot',
            name='rack_ID',
            field=models.CharField(blank=True, help_text='Identifier for the rack where this sample is stored', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalaliquot',
            name='well_ID',
            field=models.CharField(blank=True, help_text='Well position in the box (e.g., A1, B2, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalcrudesample',
            name='rack_ID',
            field=models.CharField(blank=True, help_text='Identifier for the rack where this sample is stored', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcrudesample',
            name='well_ID',
            field=models.CharField(blank=True, help_text='Well position in the box (e.g., A1, B2, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalextract',
            name='rack_ID',
            field=models.CharField(blank=True, help_text='Identifier for the rack where this sample is stored', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalextract',
            name='well_ID',
            field=models.CharField(blank=True, help_text='Well position in the box (e.g., A1, B2, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalplate',
            name='rack_ID',
            field=models.CharField(blank=True, help_text='Identifier for the rack where this plate is stored', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalplate',
            name='well_ID',
            field=models.CharField(blank=True, help_text='Well position in the box (e.g., A1, B2, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalsequencelibrary',
            name='rack_ID',
            field=models.CharField(blank=True, help_text='Identifier for the rack where this sample is stored', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalsequencelibrary',
            name='well_ID',
            field=models.CharField(blank=True, help_text='Well position in the box (e.g., A1, B2, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='rack_ID',
            field=models.CharField(blank=True, help_text='Identifier for the rack where this plate is stored', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='well_ID',
            field=models.CharField(blank=True, help_text='Well position in the box (e.g., A1, B2, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sequencelibrary',
            name='rack_ID',
            field=models.CharField(blank=True, help_text='Identifier for the rack where this sample is stored', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sequencelibrary',
            name='well_ID',
            field=models.CharField(blank=True, help_text='Well position in the box (e.g., A1, B2, etc.)', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='crudesample',
            index=models.Index(fields=['subject_id'], name='sampletrack_subject_cf1459_idx'),
        ),
    ]
