# Generated by Django 5.1.11 on 2025-07-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampletracking', '0017_remove_crudesample_sampletrack_your_id_2965c3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliquot',
            name='tube_barcode',
        ),
        migrations.RemoveField(
            model_name='crudesample',
            name='tube_barcode',
        ),
        migrations.RemoveField(
            model_name='extract',
            name='tube_barcode',
        ),
        migrations.RemoveField(
            model_name='historicalaliquot',
            name='tube_barcode',
        ),
        migrations.RemoveField(
            model_name='historicalcrudesample',
            name='tube_barcode',
        ),
        migrations.RemoveField(
            model_name='historicalextract',
            name='tube_barcode',
        ),
        migrations.RemoveField(
            model_name='historicalsequencelibrary',
            name='tube_barcode',
        ),
        migrations.RemoveField(
            model_name='sequencelibrary',
            name='tube_barcode',
        ),
    ]
