# Generated by Django 5.1.11 on 2025-09-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampletracking', '0018_remove_tube_barcode'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='extract',
            name='protocol_used',
        ),
        migrations.RemoveField(
            model_name='historicalextract',
            name='protocol_used',
        ),
        migrations.AddField(
            model_name='extract',
            name='concentration',
            field=models.FloatField(blank=True, help_text='Concentration of the extract in ng/µL', null=True),
        ),
        migrations.AddField(
            model_name='historicalextract',
            name='concentration',
            field=models.FloatField(blank=True, help_text='Concentration of the extract in ng/µL', null=True),
        ),
        migrations.AlterField(
            model_name='crudesample',
            name='sample_source',
            field=models.CharField(choices=[('Stool', 'Stool'), ('Oral', 'Oral Swab'), ('Nasal', 'Nasal Swab'), ('Skin', 'Skin Swab'), ('Blood', 'Blood'), ('Tissue', 'Tissue'), ('Other', 'Other')], default='', help_text='Source of the sample', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalcrudesample',
            name='sample_source',
            field=models.CharField(choices=[('Stool', 'Stool'), ('Oral', 'Oral Swab'), ('Nasal', 'Nasal Swab'), ('Skin', 'Skin Swab'), ('Blood', 'Blood'), ('Tissue', 'Tissue'), ('Other', 'Other')], default='', help_text='Source of the sample', max_length=100),
        ),
    ]
