# Generated by Django 5.1.11 on 2025-09-14 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampletracking', '0020_remove_crudesample_sampletrack_your_id_2965c3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliquot',
            name='rack_ID',
        ),
        migrations.RemoveField(
            model_name='crudesample',
            name='rack_ID',
        ),
        migrations.RemoveField(
            model_name='extract',
            name='rack_ID',
        ),
        migrations.RemoveField(
            model_name='historicalaliquot',
            name='rack_ID',
        ),
        migrations.RemoveField(
            model_name='historicalcrudesample',
            name='rack_ID',
        ),
        migrations.RemoveField(
            model_name='historicalextract',
            name='rack_ID',
        ),
        migrations.RemoveField(
            model_name='historicalplate',
            name='rack_ID',
        ),
        migrations.RemoveField(
            model_name='historicalsequencelibrary',
            name='rack_ID',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='rack_ID',
        ),
        migrations.RemoveField(
            model_name='sequencelibrary',
            name='rack_ID',
        ),
    ]
