# Generated by Django 5.1.11 on 2025-09-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampletracking', '0021_remove_rack_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliquot',
            name='base_id',
            field=models.CharField(blank=True, editable=False, help_text='Base ID shared among related samples.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aliquot',
            name='sample_id',
            field=models.CharField(blank=True, editable=False, help_text='Full unique sample ID (e.g., ST-250919-001-CS).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='crudesample',
            name='base_id',
            field=models.CharField(blank=True, editable=False, help_text='Base ID shared among related samples.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='crudesample',
            name='sample_id',
            field=models.CharField(blank=True, editable=False, help_text='Full unique sample ID (e.g., ST-250919-001-CS).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='extract',
            name='base_id',
            field=models.CharField(blank=True, editable=False, help_text='Base ID shared among related samples.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='extract',
            name='sample_id',
            field=models.CharField(blank=True, editable=False, help_text='Full unique sample ID (e.g., ST-250919-001-CS).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalaliquot',
            name='base_id',
            field=models.CharField(blank=True, editable=False, help_text='Base ID shared among related samples.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalaliquot',
            name='sample_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Full unique sample ID (e.g., ST-250919-001-CS).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalcrudesample',
            name='base_id',
            field=models.CharField(blank=True, editable=False, help_text='Base ID shared among related samples.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalcrudesample',
            name='sample_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Full unique sample ID (e.g., ST-250919-001-CS).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalextract',
            name='base_id',
            field=models.CharField(blank=True, editable=False, help_text='Base ID shared among related samples.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalextract',
            name='sample_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Full unique sample ID (e.g., ST-250919-001-CS).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='historicalsequencelibrary',
            name='base_id',
            field=models.CharField(blank=True, editable=False, help_text='Base ID shared among related samples.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalsequencelibrary',
            name='sample_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Full unique sample ID (e.g., ST-250919-001-CS).', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sequencelibrary',
            name='base_id',
            field=models.CharField(blank=True, editable=False, help_text='Base ID shared among related samples.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sequencelibrary',
            name='sample_id',
            field=models.CharField(blank=True, editable=False, help_text='Full unique sample ID (e.g., ST-250919-001-CS).', max_length=30, null=True),
        ),
    ]