# Generated by Django 5.1.11 on 2025-09-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampletracking', '0022_remove_crudesample_sampletrack_your_id_2965c3_idx_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='aliquot',
            name='sample_id',
            field=models.CharField(blank=True, editable=False, help_text='Full unique sample ID (e.g., ST-250919-001-CS).', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='crudesample',
            name='sample_id',
            field=models.CharField(blank=True, editable=False, help_text='Full unique sample ID (e.g., ST-250919-001-CS).', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='extract',
            name='sample_id',
            field=models.CharField(blank=True, editable=False, help_text='Full unique sample ID (e.g., ST-250919-001-CS).', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sequencelibrary',
            name='sample_id',
            field=models.CharField(blank=True, editable=False, help_text='Full unique sample ID (e.g., ST-250919-001-CS).', max_length=30, null=True, unique=True),
        ),
    ]
